{% set version = "3.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-supernova
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/supernova_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/supernova/supernova_{{ version }}.tar.gz
  sha256: f2d6649fc0674cd166b9aec34b30163517abea2f682061736e88715d37b09693

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-backports
    - r-cli
    - r-ggplot2
    - r-lifecycle
    - r-magrittr
    - r-pillar >=1.5.0
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-vctrs
  run:
    - r-base
    - r-backports
    - r-cli
    - r-ggplot2
    - r-lifecycle
    - r-magrittr
    - r-pillar >=1.5.0
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-vctrs

test:
  commands:
    - $R -e "library('supernova')"           # [not win]
    - "\"%R%\" -e \"library('supernova')\""  # [win]

about:
  home: https://github.com/UCLATALL/supernova
  license: AGPL-3.0-or-later
  summary: |
    Produces ANOVA tables in the format used by Judd, McClelland, and Ryan (2017, ISBN:
    978-1138819832) in their introductory textbook, Data Analysis. This includes proportional
    reduction in error and formatting to improve ease the transition between the book
    and R.
  license_family: AGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3'
# Type: Package
extra:
  recipe-maintainers:
    - conda-forge/r
    - adamblake

# Package: supernova
# Title: Judd, McClelland, & Ryan Formatting for ANOVA Output
# Version: 2.5.8
# Date: 2023-11-03
# Authors@R: c( person("Adam", "Blake", , "adam@coursekata.org", role = c("cre", "aut"), comment = c(ORCID = "0000-0001-7881-8652")), person("Jeff", "Chrabaszcz", role = "aut"), person("Ji", "Son", , "json2@calstatela.edu", role = "aut", comment = c(ORCID = "0000-0002-4258-4791")), person("Jim", "Stigler", , "jstigler@gmail.com", role = "aut", comment = c(ORCID = "0000-0001-6107-7827")) )
# Description: Produces ANOVA tables in the format used by Judd, McClelland, and Ryan (2017, ISBN: 978-1138819832) in their introductory textbook, Data Analysis. This includes proportional reduction in error and formatting to improve ease the transition between the book and R.
# License: AGPL (>= 3)
# URL: https://github.com/UCLATALL/supernova
# BugReports: https://github.com/UCLATALL/supernova/issues
# Depends: R (>= 3.4.0)
# Imports: backports, cli, ggplot2, lifecycle, magrittr, methods, pillar (>= 1.5.0), purrr, rlang, stringr, tibble, vctrs
# Suggests: car, covr, lintr, lme4, testthat (>= 2.1.0), tidyr, vdiffr
# Config/testthat/edition: 3
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# NeedsCompilation: no
# Packaged: 2023-11-04 17:45:29 UTC; adamblake
# Author: Adam Blake [cre, aut] (<https://orcid.org/0000-0001-7881-8652>), Jeff Chrabaszcz [aut], Ji Son [aut] (<https://orcid.org/0000-0002-4258-4791>), Jim Stigler [aut] (<https://orcid.org/0000-0001-6107-7827>)
# Maintainer: Adam Blake <adam@coursekata.org>
# Repository: CRAN
# Date/Publication: 2023-11-04 19:00:02 UTC
